name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Changed from '18' to '20'
          
      - name: Install dependencies
        run: |
          cd ANJANABA-PORTFOLIO
          npm install
          
      - name: Build Angular app
        run: |
          cd ANJANABA-PORTFOLIO
          npm run build -- --configuration production --base-href https://ranaba3343.me/
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ANJANABA-PORTFOLIO/dist/anjanaba-portfolio/browser